# Generated by Django 5.2.6 on 2025-10-01 02:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0002_alter_project_id_alter_task_id'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='task',
            options={'ordering': ['custom_order', '-created_at']},
        ),
        migrations.AddField(
            model_name='task',
            name='custom_order',
            field=models.IntegerField(db_index=True, default=0),
        ),
    ]
