# Generated by Django 5.2.6 on 2025-10-01 02:30

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0003_alter_task_options_task_custom_order'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='task',
            options={'ordering': ['-created_at']},
        ),
        migrations.RemoveField(
            model_name='task',
            name='custom_order',
        ),
        migrations.CreateModel(
            name='TaskOrder',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('context', models.CharField(choices=[('all_tasks', 'All Tasks'), ('by_project', 'By Project'), ('today', 'Today'), ('by_date', 'By Date')], max_length=20)),
                ('reference', models.CharField(blank=True, max_length=100, null=True)),
                ('position', models.IntegerField(default=0)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('task', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='order_positions', to='main.task')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='task_orders', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'ordering': ['position'],
                'indexes': [models.Index(fields=['user', 'context', 'reference', 'position'], name='main_taskor_user_id_6076da_idx')],
                'unique_together': {('user', 'context', 'reference', 'task')},
            },
        ),
    ]
